export const pollenTypes = {
  TREES: 'arboles',
  GRASS: 'hierbas',
  MUSHROOMS: 'hongos',
};

export const pollenIds = {
  TREES: 'a',
  GRASS: 'h',
  MUSHROOMS: 'g',
};

export const pollenNames = {
  TREES: 'Árboles',
  GRASS: 'Hierbas',
  MUSHROOMS: 'Hongos',
};

export const pollenLevels = {
  HIGH: 'alto',
  MEDIUM: 'medio',
  LOW: 'bajo',
};

export const generiQuestionsTypes = {
  NASAL: 'NASAL_DISCONFORT',
  EYES: 'EYES_DISCONFORT',
  COUGH: 'RECURRENT_CAUGH',
};

export const gendersTypes = {
  FEMALE: 'F',
  MALE: 'M',
  OTHER: 'O',
};

export const symptomsLevel = {
  MEDIUM: 'algo',
  HIGH: ['mucho', 'si'],
};

export const capital = 'MONTEVIDEO';

export const departments = [
  capital,
  'ARTIGAS',
  'CANELONES',
  'COLONIA',
  'DURAZNO',
  'FLORIDA',
  'LAVALLEJA',
  'PAYSANDU',
  'RIO NEGRO',
  'RIVERA',
  'ROCHA',
  'SALTO',
  'SAN JOSE',
  'SORIANO',
  'TREINTA Y TRES',
  'LIMITE CONTESTADO',
  'MALDONADO',
  'CERRO LARGO',
  'TACUAREMBO',
];

export const zones = [
  'Abayubá',
  'Aguada',
  'Aires Puros',
  'Arroyo Seco',
  'Atahualpa',
  'Barrio Sur',
  'Bañados de Carrasco',
  'Bella Vista',
  'Belvedere',
  'Bolívar',
  'Brazo Oriental',
  'Buceo',
  'Capurro',
  'Carrasco Norte',
  'Carrasco',
  'Casabó',
  'Casavalle',
  'Castro',
  'Centro',
  'Cerrito de la Victoria',
  'Ciudad Vieja',
  'Colón Centro y Noroeste',
  'Colón Sureste',
  'Conciliación',
  'Cordón',
  'Flor de Maroñas',
  'Goes',
  'Ituzaingó',
  'Jacinto Vera',
  'Jardines del Hipódromo',
  'La Blanqueada',
  'La Comercial',
  'La Figurita',
  'La Paloma',
  'La Teja',
  'Larrañaga',
  'Las Acacias',
  'Las Canteras',
  'Lavalleja',
  'Lezica',
  'Malvín Norte',
  'Malvín',
  'Manga Rural',
  'Manga',
  'Marconi',
  'Maroñas',
  'Melilla',
  'Mercado Modelo',
  'Nueva Savona',
  'Nuevo París',
  'Pajas Blancas',
  'Palermo',
  'Parque Batlle',
  'Parque Rodó',
  'Paso de la Arena',
  'Paso de las Duranas',
  'Paso Molino',
  'Peñarol',
  'Piedras Blancas',
  'Pocitos',
  'Prado',
  'Pueblo Victoria',
  'Punta Carretas',
  'Punta de Rieles',
  'Punta Gorda',
  'Pérez Castellanos',
  'Reducto',
  'Retiro',
  'Santiago Vázquez',
  'Sayago',
  'Toledo Chico',
  'Tomkinson',
  'Tres Cruces',
  'Tres Ombúes',
  'Unión',
  'Villa del Cerro',
  'Villa Dolores',
  'Villa Española',
  'Villa García',
  'Villa Muñoz',
];

export const mapApplications = {
  SYGIC: 'sygic',
  TAXIS_99: 'taxis_99',
  TOMTOM: 'tomtom',
  WAZE: 'waze',
  CABIFY: 'cabify',
  GAODE: 'gaode',
  CITY_MAPPER: 'citymapper',
  YANDEX: 'yandex',
  HERE_MAPS: 'here_maps',
  NAVIGON: 'navigon',
  LYFT: 'lyft',
  TRANSIT_APP: 'transit_app',
  MAPS_ME: 'maps_me',
  APPLE_MAPS: 'apple_maps',
  UBER: 'uber',
  GOOGLE_MAPS: 'google_maps',
  BAIDU: 'baidu',
  MOOVIT: 'moovit',
};
